name: CI
on: [push]

jobs:

  build-lnx:
    runs-on: ubuntu-latest

    steps:

    - name: apt-get install
      run: DEBIAN_FRONTEND=noninteractive sudo -E apt-get -y install bison flex gettext gperf groff ninja-build python3-pip python3-setuptools tcl
    - name: pip install meson
      run: sudo -E pip3 install meson==0.51.2

    - name: git config
      run: |
        git config --global url."git://git.savannah.gnu.org/".insteadOf "https://git.savannah.gnu.org/git/"
        git config --global url."git://git.savannah.nongnu.org/".insteadOf "https://git.savannah.nongnu.org/git/"
        git config --global advice.detachedHead false
    - uses: actions/checkout@v1
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: make Linux server deb
      run: make -j3 -C pkg-lnx deb
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd.deb
        path: pkg-lnx/orchidd.deb
    - name: make Linux server rpm
      run: make -j3 -C pkg-lnx rpm
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd.rpm
        path: pkg-lnx/orchidd.rpm
